### ISSUE TITLE
Will this crate support windows system later?

### ISSUE THREAD

**Issue by haofeiliang** [pop-os/async-fetcher#15]
After I found it on crates.io, I tried to build the fetcher on my windows pc. But I get error during compile. Some dependencies like "ifaces" only can be used on Linux machines. Will this powerful crate support windows system later?
![image](https://user-images.githubusercontent.com/13299908/154274606-dbbb1788-fa53-4173-b090-922d394b24ec.png)

**Comment by mmstick** [comment]
I could support Windows in the future, but Linux is the platform I develop for. I think this would just require swapping the isahc HTTP client out for Reqwest (optionally).

**Comment by haofeiliang** [comment]
Thanks. Thanks for youe reply.

**Comment by 4JX** [comment]
Did a quick translation of the code to use reqwest [here](https://github.com/4JX/async-fetcher/tree/reqwest), and also left a [version](https://github.com/4JX/async-fetcher/tree/reqwest-feature) with both dependencies as features. Wouldn't mind to PR the latter, but further refactoring is most likely still possible.

**Comment by mmstick** [comment]
Having the option to choose between an isahc and reqwest feature would be great!
