### ISSUE TITLE
Unbounded connections to a server?

### ISSUE THREAD

**Issue by FauxFaux** [pop-os/async-fetcher#9]
It appears that a naive use of this library results in an unbounded number of connections being made to the target(s).

For code like:
```
let futures = urls.map(|url| AsyncFetcher::new(&client, url)
   .request_to_path(...)
   .then_download(...)
   .then_rename()
   .into_future());
tokio::runtime::Runtime::new()?.block_on(futures::future::join_all(futures))?;
```

.. I see `N` concurrent TLS handshakes happening in Wireshark, and a whole bunch of CPU usage.
(The (single) target server also returns weird connection errors and sends me unexpected ACKs, who knows what's going on there; maybe some DoS protection kicking in.)

Would limiting this be in scope for `async-fetcher`? It's not exactly easy to implement in tokio's API (what is?). Maybe it should live in `hyper`?

What would be a reasonable behaviour? I was expecting... `http2` pipelining (all over the same connection) if supported, and .. a limit of 6 connections per server (like browsers) otherwise?

**Comment by mmstick** [comment]
A join future will execute every future in the iterator in parallel. The thread pool-backed tokio runtime will also use up to the number of CPUs in the system (default value) as the max number of threads to use for parallel processing, spreading those tasks via work-stealing.

To limit the number of futures being executed at once, you'll want to use a buffered stream instead:

```rust
use futures::stream::futures_unordered;

let stream = futures_unordered(iterator_of_futures)
    .buffer_unordered(num_concurrent);
```

You can decide how to convert that stream into a future for the runtime. The `collect` method will collect it as a `Vec<Self::Item>`, same as `join_all`. The `for_each` method will collect into a `()`.  The `fold` method will let you collect however you want.

```rust
let future = stream.collect();
Runtime::new()?.block_on(future)?
```

**Comment by FauxFaux** [comment]
I can't get that to typecheck with `futures_unordered(_).buffer_unordered(_)`. It needs something that implements `IntoFuture`, which `CompletedState<>` doesn't, and `Future<Item = ()>` doesn't implement `IntoFuture<Future = Self>` either.

I ended up with (https://github.com/FauxFaux/fappa/commit/7c8af6f9978da3ddfb357d5e68d57b332dc2beb9):

```rust
    let client = Arc::new(Client::new());

    let s = stream::iter_ok(work)
        .map(move |(url, dest, temp)| {
            AsyncFetcher::new(&client, url)
                .request_to_path(dest.into())
                .then_download(temp.into())
                .then_rename()
                .into_future()
        })
        .buffer_unordered(6);

    let mut runtime = tokio::runtime::Runtime::new()?;

    runtime
        .block_on(s.into_future())
        .map_err(|(fetch, _todo)| fetch)?;
```

i.e. create the work items in advance, then make them into a simple (infalliable linear) stream, and `map` those into futures, which can then be buffered.

I'm not a fan of that solution, but it does work for my case (multiple downloads from a single server).

**Comment by mmstick** [comment]
The 0.1 futures & streams are a bit unergonomic at the moment. Seems 0.3 will be simplifying a lot of scenarios, including this one (only requires that the stream returns a `Future`, rather than an `IntoFuture`). Even the `tokio` runtime will be optional as futures will provide a default executor and thread pool for executing futures.

In the meantime, it may be possible to create an `AsyncManager` type for constructing batches of `AsyncFetcher` futures as a buffered stream so that the caller doesn't need to create one by hand.

**Comment by FauxFaux** [comment]
A note to anyone reading the code above: `Stream.into_future()` is not correct; it only waits for up to one element to complete, and leaves the remainder hanging. `collect()` is more useful.
